name: er
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bullet-cpp=3.25
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - expat=2.7.1
  - fonttools=4.61.1
  - freetype=2.13.3
  - jpeg=9e
  - kiwisolver=1.4.9
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcxx=19.1.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.11.0
  - libopenblas=0.3.30
  - libpng=1.6.39
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.6.0
  - packaging=25.0
  - pillow=11.1.0
  - pip=25.3
  - pthread-stubs=0.4
  - pybullet=3.25
  - pyparsing=3.3.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - qhull=2020.2
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tornado=6.5.4
  - tzdata=2025b
  - unicodedata2=17.0.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
prefix: /opt/miniconda3/envs/er
